/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-dim": "#005a53",
        "secondary-dim": "#a00047",
        "surface-bright": "#f5f6f8",
        "on-error": "#ffefef",
        "on-background": "#2c2f31",
        "on-tertiary": "#bffff5",
        "surface-dim": "#d1d5d8",
        "on-primary-fixed": "#000005",
        "primary-container": "#929bfa",
        "on-tertiary-fixed-variant": "#00655d",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#00675f",
        "outline": "#757779",
        "outline-variant": "#abadaf",
        "on-secondary-container": "#910040",
        "tertiary-container": "#81f3e5",
        "on-secondary": "#ffeff0",
        "surface-container-high": "#e0e3e5",
        "on-error-container": "#510017",
        "primary": "#4953ac",
        "on-primary-fixed-variant": "#18217d",
        "surface-container": "#e6e8eb",
        "on-tertiary-fixed": "#004640",
        "tertiary-fixed": "#81f3e5",
        "secondary": "#b40953",
        "on-secondary-fixed": "#6d002e",
        "primary-dim": "#3d469f",
        "primary-fixed": "#929bfa",
        "inverse-surface": "#0c0f10",
        "surface-container-low": "#eff1f3",
        "inverse-on-surface": "#9b9d9f",
        "secondary-fixed": "#ffc2ce",
        "on-surface-variant": "#595c5e",
        "primary-fixed-dim": "#858eec",
        "secondary-fixed-dim": "#ffadbf",
        "error-dim": "#a70138",
        "surface-tint": "#4953ac",
        "on-primary-container": "#0b1574",
        "on-primary": "#f3f1ff",
        "secondary-container": "#ffc2ce",
        "on-secondary-fixed-variant": "#a20048",
        "surface": "#f5f6f8",
        "on-tertiary-container": "#005a53",
        "on-surface": "#2c2f31",
        "error-container": "#f74b6d",
        "inverse-primary": "#929bfa",
        "surface-container-highest": "#dadde0",
        "surface-variant": "#dadde0",
        "error": "#b41340",
        "background": "#f5f6f8",
        "tertiary-fixed-dim": "#72e4d7"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.75rem",
        lg: "1.25rem",
        xl: "2rem",
        full: "9999px",
      },
      keyframes: {
        fadeIn: { "0%": { opacity: 0, transform: "translateY(12px)" }, "100%": { opacity: 1, transform: "translateY(0)" } },
        slideDown: { "0%": { opacity: 0, transform: "translateY(-8px)" }, "100%": { opacity: 1, transform: "translateY(0)" } },
        pulse2: { "0%,100%": { opacity: 1 }, "50%": { opacity: 0.5 } },
        scaleIn: { "0%": { transform: "scale(0.95)", opacity: 0 }, "100%": { transform: "scale(1)", opacity: 1 } },
      },
      animation: {
        fadeIn: "fadeIn 0.4s ease-out",
        slideDown: "slideDown 0.25s ease-out",
        pulse2: "pulse2 1.5s ease-in-out infinite",
        scaleIn: "scaleIn 0.3s ease-out",
      },
    },
  },
  plugins: [],
};
